### PR TITLE
fix: Remove `validium_mode_example` crate

### PR DESCRIPTION
**Pull request by ilitteri**
This crate was meant for development. Nevertheless, we now have #144 to test the same.

### CODE REVIEW

**Review by jordibonet-lambdaclass — APPROVED** [review]
LGTM!

**Review by toni-calvin — APPROVED** [review]
LGTM!

**Comment by mationorato** [comment]
We should move this example to another branch. It is still useful and practical.

**Comment by mationorato** [comment]
I moved it here https://github.com/lambdaclass/zksync-era/pull/175

Resolves #163.

Now we can merge.

**Pull request merged**
